package exchange

// SignalType represents the type of trading signal
type SignalType int

const (
	SignalNone SignalType = iota
	SignalLong
	SignalShort
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Index  int        `json:"index"`
	Type   SignalType `json:"type"`
	Price  float64    `json:"price"`
	Time   int64      `json:"time"`
	Reason string     `json:"reason"`
}

// Position represents a trading position
type Position struct {
	EntryIndex    int     `json:"entryIndex"`
	EntryPrice    float64 `json:"entryPrice"`
	EntryTime     int64   `json:"entryTime"`
	ExitIndex     int     `json:"exitIndex"`
	ExitPrice     float64 `json:"exitPrice"`
	ExitTime      int64   `json:"exitTime"`
	Side          string  `json:"side"` // "long" or "short"
	Size          float64 `json:"size"`
	PnL           float64 `json:"pnl"`
	PnLPercentage float64 `json:"pnlPercentage"`
	IsOpen        bool    `json:"isOpen"`
	ExitReason    string  `json:"exitReason"`
	MaxDrawdown   float64 `json:"maxDrawdown"`
	MaxProfit     float64 `json:"maxProfit"`
}

// ActivePosition represents an open position from the exchange
type ActivePosition struct {
	Coin           string  `json:"coin"`
	Side           string  `json:"side"`
	EntryPrice     float64 `json:"entryPrice"`
	PositionValue  float64 `json:"positionValue"`
	UnrealizedPnL  float64 `json:"unrealizedPnL"`
	ReturnOnEquity float64 `json:"returnOnEquity"`
	Leverage       float64 `json:"leverage"`
	LiquidationPx  float64 `json:"liquidationPx"`
	MarginUsed     float64 `json:"marginUsed"`
}

// PortfolioSummary contains account balance and position information
type PortfolioSummary struct {
	Balance   BalanceInfo      `json:"balance"`
	Positions []ActivePosition `json:"positions"`
}

// BalanceInfo contains account balance details
type BalanceInfo struct {
	AccountValue    string `json:"accountValue"`
	TotalMarginUsed string `json:"totalMarginUsed"`
	TotalNtlPos     string `json:"totalNtlPos"`
	TotalRawUsd     string `json:"totalRawUsd"`
	WithdrawAvail   string `json:"withdrawAvail"`
}

// OrderResponse represents the response from placing an order
type OrderResponse struct {
	Success bool
	Message string
}
