// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hyperliquid} from '../models';
import {exchange} from '../models';
import {strategy} from '../models';
import {engine} from '../models';
import {position} from '../models';

export function FetchCandles(arg1:string,arg2:string,arg3:number):Promise<hyperliquid.Candles>;

export function FetchCandlesBefore(arg1:string,arg2:string,arg3:number,arg4:number):Promise<hyperliquid.Candles>;

export function GetActivePositions():Promise<Array<exchange.ActivePosition>>;

export function GetAvailableStrategies():Promise<Array<strategy.Metadata>>;

export function GetPortfolioSummary():Promise<exchange.PortfolioSummary>;

export function GetRunningStrategies():Promise<Array<engine.RunningStrategyInfo>>;

export function GetStrategyParams(arg1:string):Promise<strategy.Metadata>;

export function GetWalletAddress():Promise<string>;

export function InvalidateCache():Promise<void>;

export function InvalidateCacheForSymbol(arg1:string):Promise<void>;

export function StopLiveStrategy(arg1:string):Promise<void>;

export function StrategyBacktest(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Record<string, any>,arg6:position.ExecutionConfig):Promise<engine.BacktestResult>;

export function StrategyRun(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, any>,arg6:position.ExecutionConfig):Promise<void>;
