// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchCandles(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchCandles'](arg1, arg2, arg3);
}

export function FetchCandlesBefore(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FetchCandlesBefore'](arg1, arg2, arg3, arg4);
}

export function GetActivePositions() {
  return window['go']['app']['App']['GetActivePositions']();
}

export function GetAvailableStrategies() {
  return window['go']['app']['App']['GetAvailableStrategies']();
}

export function GetPortfolioSummary() {
  return window['go']['app']['App']['GetPortfolioSummary']();
}

export function GetRunningStrategies() {
  return window['go']['app']['App']['GetRunningStrategies']();
}

export function GetStrategyParams(arg1) {
  return window['go']['app']['App']['GetStrategyParams'](arg1);
}

export function GetWalletAddress() {
  return window['go']['app']['App']['GetWalletAddress']();
}

export function InvalidateCache() {
  return window['go']['app']['App']['InvalidateCache']();
}

export function InvalidateCacheForSymbol(arg1) {
  return window['go']['app']['App']['InvalidateCacheForSymbol'](arg1);
}

export function StopLiveStrategy(arg1) {
  return window['go']['app']['App']['StopLiveStrategy'](arg1);
}

export function StrategyBacktest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StrategyBacktest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StrategyRun(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['StrategyRun'](arg1, arg2, arg3, arg4, arg5, arg6);
}
